import { createPickup, createShipping, toggleSetting, updateShippingTransit } from "../actions";
import { AdminNotice } from "@/components/admin-notice";
import { AdminOrderSoundSettings } from "@/components/admin-order-sound";
import { pickupLocations, shippingZones } from "@/lib/admin/data";
import { euro } from "@/lib/admin/format";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [pickup, shipping, notice] = await Promise.all([pickupLocations(), shippingZones(), searchParams]);
  return <main className="admin-content">
    <div className="admin-page-heading"><div><span className="admin-kicker">CONFIGURATION</span><h1>Settings</h1><p>Manage order alerts, pickup locations, and delivery costs.</p></div></div>
    <AdminNotice {...notice} />
    <AdminOrderSoundSettings />
    <div className="admin-summary-strip"><div><strong>{pickup.filter((item) => item.active).length}</strong><span>Active pickup locations</span></div><div><strong>{shipping.filter((item) => item.active).length}</strong><span>Active shipping zones</span></div><div><strong>{pickup.length + shipping.length}</strong><span>Total fulfillment options</span></div></div>
    <div className="admin-two-column">
      <section className="admin-panel"><div className="panel-title"><h2>Pickup locations</h2><span>{pickup.length} total</span></div><p className="form-help">Active locations are available when a customer chooses pickup.</p><div className="admin-list">{pickup.length ? pickup.map((item) => <div className="admin-list-row" key={item.id}><div><strong>{item.name}</strong><small>{item.address}<br />{item.opening_hours}</small><span className={item.active ? "status-pill positive" : "status-pill"}>{item.active ? "Active" : "Inactive"}</span></div><form action={toggleSetting}><input type="hidden" name="kind" value="pickup" /><input type="hidden" name="id" value={item.id} /><button className="admin-secondary" type="submit">{item.active ? "Disable" : "Enable"}</button></form></div>) : <div className="admin-empty">No pickup locations configured.</div>}</div><form action={createPickup} className="admin-form form-divider"><h3>Add pickup location</h3><label>Location name<input name="name" maxLength={120} required /></label><label>Address<input name="address" maxLength={500} required /></label><label>Opening hours<textarea name="opening_hours" rows={3} maxLength={500} required placeholder="Mon–Fri, 09:00–17:00" /></label><button className="admin-primary" type="submit">Add location</button></form></section>
      <section className="admin-panel"><div className="panel-title"><h2>Shipping zones</h2><span>{shipping.length} total</span></div><p className="form-help">Active zones and fees appear at checkout. Transit time is in business days after production.</p><div className="admin-list">{shipping.length ? shipping.map((item) => <div className="admin-list-row" key={item.id}><div><strong>{item.name} · {euro(item.fee_cents)}</strong><small>{item.description}</small><span className={item.active ? "status-pill positive" : "status-pill"}>{item.active ? "Active" : "Inactive"}</span><form action={updateShippingTransit} className="admin-form compact-form"><input type="hidden" name="id" value={item.id} /><div className="form-row"><label>Transit from<input name="transit_min_days" type="number" min="0" max="30" defaultValue={item.transit_min_days ?? ""} /></label><label>Transit to<input name="transit_max_days" type="number" min="0" max="30" defaultValue={item.transit_max_days ?? ""} /></label></div><button className="admin-secondary" type="submit">Save transit time</button></form></div><form action={toggleSetting}><input type="hidden" name="kind" value="shipping" /><input type="hidden" name="id" value={item.id} /><button className="admin-secondary" type="submit">{item.active ? "Disable" : "Enable"}</button></form></div>) : <div className="admin-empty">No shipping zones configured.</div>}</div><form action={createShipping} className="admin-form form-divider"><h3>Add shipping zone</h3><label>Zone name<input name="name" maxLength={120} required placeholder="Kosovo" /></label><label>Description<input name="description" maxLength={500} placeholder="All municipalities" /></label><label>Delivery fee (€)<input name="fee" inputMode="decimal" required placeholder="3.00" /></label><div className="form-row"><label>Transit from (business days)<input name="transit_min_days" type="number" min="0" max="30" /></label><label>Transit to (business days)<input name="transit_max_days" type="number" min="0" max="30" /></label></div><button className="admin-primary" type="submit">Add shipping zone</button></form></section>
    </div>
  </main>;
}
