import { createPickup, createShipping, toggleSetting } from "../actions";
import { AdminNotice } from "@/components/admin-notice";
import { pickupLocations, shippingZones } from "@/lib/admin/data";
import { euro } from "@/lib/admin/format";

export default async function SettingsPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [pickup, shipping, notice] = await Promise.all([pickupLocations(), shippingZones(), searchParams]);
  return <main className="admin-content"><div className="admin-page-heading"><div><span className="admin-kicker">CONFIGURATION</span><h1>Settings</h1><p>Manage where customers collect orders and what delivery costs.</p></div></div><AdminNotice {...notice} /><div className="admin-two-column"><section className="admin-panel"><div className="panel-title"><h2>Pickup locations</h2><span>{pickup.length} total</span></div><div className="admin-list">{pickup.map((item) => <div className="admin-list-row" key={item.id}><div><strong>{item.name}</strong><small>{item.address}<br />{item.opening_hours}</small></div><form action={toggleSetting}><input type="hidden" name="kind" value="pickup" /><input type="hidden" name="id" value={item.id} /><button className={item.active ? "status-pill positive button-pill" : "status-pill button-pill"} type="submit">{item.active ? "Active" : "Inactive"}</button></form></div>)}</div><form action={createPickup} className="admin-form form-divider"><h3>Add pickup location</h3><label>Location name<input name="name" maxLength={120} required /></label><label>Address<input name="address" maxLength={500} required /></label><label>Opening hours<textarea name="opening_hours" rows={3} maxLength={500} required placeholder="Mon–Fri, 09:00–17:00" /></label><button className="admin-primary" type="submit">Add location</button></form></section><section className="admin-panel"><div className="panel-title"><h2>Shipping zones</h2><span>{shipping.length} total</span></div><div className="admin-list">{shipping.map((item) => <div className="admin-list-row" key={item.id}><div><strong>{item.name} · {euro(item.fee_cents)}</strong><small>{item.description}</small></div><form action={toggleSetting}><input type="hidden" name="kind" value="shipping" /><input type="hidden" name="id" value={item.id} /><button className={item.active ? "status-pill positive button-pill" : "status-pill button-pill"} type="submit">{item.active ? "Active" : "Inactive"}</button></form></div>)}</div><form action={createShipping} className="admin-form form-divider"><h3>Add shipping zone</h3><label>Zone name<input name="name" maxLength={120} required placeholder="Kosovo" /></label><label>Description<input name="description" maxLength={500} placeholder="All municipalities" /></label><label>Delivery fee (€)<input name="fee" inputMode="decimal" required placeholder="3.00" /></label><button className="admin-primary" type="submit">Add shipping zone</button></form></section></div></main>;
}
