import { createQuote, updateQuote } from "../actions";
import { AdminNotice } from "@/components/admin-notice";
import { quotes } from "@/lib/admin/data";
import { dateTime, euro } from "@/lib/admin/format";

const statuses = ["new", "reviewing", "sent", "accepted", "declined"];

export default async function QuotesPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [items, notice] = await Promise.all([quotes(), searchParams]);
  return <main className="admin-content"><div className="admin-page-heading"><div><span className="admin-kicker">SALES</span><h1>Quotes</h1><p>Record custom requests and track the offer you send to a customer.</p></div></div><AdminNotice {...notice} /><div className="admin-two-column wide-first"><section className="admin-panel"><div className="panel-title"><h2>Quote requests</h2><span>{items.length} shown</span></div>{items.length ? <div className="quote-list">{items.map((item) => <article className="quote-card" key={item.id}><div className="quote-heading"><div><strong>{item.customer_name}</strong><small>{item.customer_email} · {dateTime(item.created_at)}</small></div><span className="status-pill">{item.status}</span></div><p>{item.details}</p><form action={updateQuote} className="admin-form compact-form"><input type="hidden" name="id" value={item.id} /><div className="form-row"><label>Status<select name="status" defaultValue={item.status}>{statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select></label><label>Quoted amount (€)<input name="amount" inputMode="decimal" defaultValue={item.amount_cents == null ? "" : (item.amount_cents / 100).toFixed(2)} placeholder="Not set" /></label></div><label>Internal note<input name="admin_note" defaultValue={item.admin_note} /></label><div className="quote-footer"><span>Current offer: {euro(item.amount_cents)}</span><button className="admin-secondary" type="submit">Save quote</button></div></form></article>)}</div> : <div className="admin-empty">No quote requests yet. You can record a request using the form.</div>}</section><section className="admin-panel"><div className="panel-title"><h2>Record a quote request</h2></div><form action={createQuote} className="admin-form"><label>Customer name<input name="customer_name" maxLength={120} required /></label><label>Customer email<input name="customer_email" type="email" maxLength={254} required /></label><label>Request details<textarea name="details" rows={6} required /></label><button className="admin-primary" type="submit">Create quote</button></form></section></div></main>;
}
