import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { updateDesignRequest } from "../../actions";
import { sendDesignQuote } from "../../quotes/actions";
import { AdminNotice } from "@/components/admin-notice";
import { designRequest } from "@/lib/admin/data";
import { dateTime } from "@/lib/admin/format";
import { euro } from "@/lib/admin/format";
import { getPool } from "@/lib/db";
import { openOrder } from "@/app/admin/orders/actions";

const productNames = { pens: "Pens", shirts: "T-shirts", hats: "Hats" };
const statuses = ["new", "reviewing", "quoted", "closed", "cancelled"];

type LinkedQuote = { id: string; status: string; amount_cents: number | null; details: string; customer_note: string; revision: number; notification_email_status: string; order_id: string | null; has_proof: boolean };

export default async function DesignRequestPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ saved?: string; error?: string; email?: string }> }) {
  const { id } = await params;
  const [item, notice, linked] = await Promise.all([designRequest(id), searchParams, getPool().query<LinkedQuote>("SELECT id,status,amount_cents,details,customer_note,revision,notification_email_status,order_id,(proof_png IS NOT NULL) AS has_proof FROM quotes WHERE design_request_id=$1", [id])]);
  if (!item) notFound();
  const quote = linked.rows[0];
  const layers = Array.isArray(item.design_data?.layers) ? item.design_data.layers : [];
  const personalizations = Array.isArray(item.design_data?.personalizations) ? item.design_data.personalizations : [];
  const requestedColors = Array.isArray(item.design_data?.productColors) ? item.design_data.productColors : [item.product_color];
  return <main className="admin-content">
    <Link href="/admin/design-requests" className="admin-back">← All design requests</Link>
    <div className="admin-page-heading"><div><span className="admin-kicker">CUSTOMER DESIGN</span><h1>Request #{item.id.slice(0, 8)}</h1><p>Submitted {dateTime(item.created_at)} · {(item.product_name ?? productNames[item.product_type])} · {item.quantity} requested</p></div></div>
    <AdminNotice {...notice} />
    {notice.email && notice.email !== "sent" && <div className="admin-notice error" role="alert">Quote is available in the customer account, but email was {notice.email === "not_configured" ? "not configured" : "not sent"}. Contact the customer directly.</div>}
    <div className="admin-two-column wide-first">
      <section className="admin-panel"><div className="panel-title"><h2>Design preview{item.product_type === "shirts" ? ` · ${item.design_data?.previewSide ?? "front"}` : ""}</h2><a className="table-link" href={`/admin/design-requests/${item.id}/preview`} download={`perty-design-${item.id.slice(0, 8)}.png`}>Download PNG ↓</a></div><Image unoptimized src={`/admin/design-requests/${item.id}/preview`} width={1000} height={item.design_data?.previewHeight ?? 420} alt={`${(item.product_name ?? productNames[item.product_type])} design submitted by ${item.customer_name}`} className="design-request-preview" /><p className="form-help">Visual mockup. Check the original design details before production.</p><div className="design-request-layers"><h3>Design layers</h3>{layers.length ? <ul>{layers.map((layer, index) => <li key={index}><strong>{item.product_type === "shirts" ? `${layer.side ?? "front"}: ` : ""}</strong>{layer.kind === "text" ? `Text: ${layer.text ?? ""}` : <><span>Artwork · </span><a className="table-link" href={`/admin/design-requests/${item.id}/artwork/${index}`}>Download artwork</a></>}</li>)}</ul> : <p>No layers saved.</p>}{personalizations.length > 0 && <><h3>Names & numbers</h3><ul>{personalizations.map((entry, index) => <li key={index}>{entry.name || "—"} · #{entry.number || "—"} · Size {entry.size}</li>)}</ul></>}</div></section>
      <div><section className="admin-panel summary-panel"><div className="panel-title"><h2>Customer and product</h2></div><dl><div><dt>Name</dt><dd>{item.customer_name}</dd></div><div><dt>Email</dt><dd><a href={`mailto:${item.customer_email}`}>{item.customer_email}</a></dd></div><div><dt>Phone</dt><dd>{item.customer_phone || "—"}</dd></div><div><dt>Product</dt><dd>{(item.product_name ?? productNames[item.product_type])}</dd></div><div><dt>Quantity</dt><dd>{item.quantity}</dd></div>{item.design_data?.photoMockup ? <div><dt>Product photo</dt><dd>Uploaded catalog photo</dd></div> : <div><dt>Product color</dt><dd><span className="design-request-color" style={{ backgroundColor: item.product_color }} /> {item.product_color}</dd></div>}</dl>{item.notes && <div className="design-request-notes"><strong>Customer notes</strong><p>{item.notes}</p></div>}</section>
        {!item.design_data?.photoMockup && <section className="admin-panel"><div className="panel-title"><h2>Requested {(item.product_name ?? productNames[item.product_type]).toLowerCase()} colors</h2></div><ul>{requestedColors.map((color, index) => <li key={`${color}-${index}`}><span className="design-request-color" style={{ backgroundColor: color }} /> {color}</li>)}</ul></section>}
        <section className="admin-panel"><div className="panel-title"><h2>Customer quote</h2>{quote && <span className="status-pill">{quote.status.replaceAll("_", " ")}</span>}</div>{quote && <><p>Revision {quote.revision} · {euro(quote.amount_cents)} for {item.quantity} items</p><p className="form-help">Email: {quote.notification_email_status.replaceAll("_", " ")}</p>{quote.has_proof && <><p className="form-help">Final proof sent to the customer:</p><Image unoptimized src={`/admin/quotes/${quote.id}/preview`} width={1000} height={420} alt="Final quote proof" className="design-request-preview" /></>}{quote.customer_note && <div className="design-request-notes"><strong>Customer requested changes</strong><p>{quote.customer_note}</p></div>}{quote.order_id && <form action={openOrder} className="order-open-form"><input type="hidden" name="id" value={quote.order_id} /><button className="table-link" type="submit">Open accepted order →</button></form>}</>}
          {!item.user_id ? <p className="form-help">This request was submitted without an account. Ask the customer to sign in and submit the design again for online quote approval.</p> : item.status === "cancelled" || item.status === "closed" || quote?.status === "accepted" ? <p className="form-help">This request can no longer receive a quote.</p> : <form action={sendDesignQuote} className="admin-form"><input type="hidden" name="request_id" value={item.id} /><label>Total quote for all {item.quantity} items (€)<input name="amount" inputMode="decimal" required defaultValue={quote?.amount_cents != null ? (quote.amount_cents / 100).toFixed(2) : ""} placeholder="100.00" /></label><p className="form-help">Enter the full product price for all {item.quantity} items. Delivery is added if the customer selects it. The total must split evenly into a per-item price.</p><label>Offer details for customer<textarea name="details" rows={5} minLength={5} maxLength={5000} required defaultValue={quote?.details ?? ""} placeholder="Materials, print method, turnaround time, and what is included" /></label><label>Final preview PNG (optional)<input name="proof_png" type="file" accept="image/png" /></label><p className="form-help">Upload a revised proof up to 2 MB. If left empty, the customer sees the submitted preview{quote?.has_proof ? " or the previous proof" : ""}.</p><button type="submit" className="admin-primary">{quote ? "Send revised quote" : "Send quote for approval"}</button></form>}</section>
        <section className="admin-panel"><div className="panel-title"><h2>Manage request</h2></div><form action={updateDesignRequest} className="admin-form"><input type="hidden" name="id" value={item.id} />{quote && ["sent", "changes_requested", "accepted"].includes(quote.status) ? <><input type="hidden" name="status" value={item.status} /><p className="form-help">Status is managed by the quote: {item.status}.</p></> : <label>Status<select name="status" defaultValue={item.status}>{statuses.map((status) => <option key={status} value={status}>{status}</option>)}</select></label>}<label>Internal note<textarea name="admin_note" rows={5} defaultValue={item.admin_note} maxLength={5000} /></label><button type="submit" className="admin-primary">Save request</button></form></section></div>
    </div>
  </main>;
}
