import { reviewArtwork } from "../actions";
import { AdminNotice } from "@/components/admin-notice";
import { artwork } from "@/lib/admin/data";
import { dateTime } from "@/lib/admin/format";

export default async function FilesPage({ searchParams }: { searchParams: Promise<{ saved?: string; error?: string }> }) {
  const [items, notice] = await Promise.all([artwork(), searchParams]);
  return <main className="admin-content"><div className="admin-page-heading"><div><span className="admin-kicker">DESIGN STUDIO</span><h1>Artwork files</h1><p>Review customer artwork records. Secure upload and download arrive with the editor milestone.</p></div></div><AdminNotice {...notice} /><section className="admin-panel table-panel"><div className="panel-title"><h2>Customer files</h2><span>{items.length} shown</span></div>{items.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>File</th><th>Customer</th><th>Type</th><th>Size</th><th>Uploaded</th><th>Review</th></tr></thead><tbody>{items.map((item) => <tr key={item.id}><td><strong>{item.original_name}</strong></td><td>{item.customer_email ?? "Guest"}</td><td>{item.mime_type}</td><td>{(Number(item.size_bytes) / 1024 / 1024).toFixed(1)} MB</td><td>{dateTime(item.created_at)}</td><td><form action={reviewArtwork} className="inline-management"><input type="hidden" name="id" value={item.id} /><select name="status" defaultValue={item.status} aria-label={`Review status for ${item.original_name}`}><option value="pending">Pending</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select><button className="admin-secondary" type="submit">Save</button></form></td></tr>)}</tbody></table></div> : <div className="admin-empty">No artwork files yet. Upload handling will be connected to the customer editor.</div>}</section></main>;
}
