import Link from "next/link";
import Image from "next/image";
import { requireUser } from "@/lib/auth/guard";
import { SignOutButton } from "@/components/sign-out-button";
import { getPool } from "@/lib/db";
import { dateTime, euro } from "@/lib/admin/format";
import { deleteDesign, duplicateDesign, shareDesign, stopSharingDesign } from "./actions";
import { ShareLink } from "./share-link";

type SavedRow = { id: string; name: string; product_id: string | null; product_name: string; product_slug: string; updated_at: Date; product_status: string | null; share_token: string | null };
type QuoteRow = { id: string; status: string; amount_cents: number | null; revision: number; sent_at: Date | null; product_name: string | null; product_type: string; quantity: number };

export default async function AccountPage({ searchParams }: { searchParams: Promise<{ section?: string }> }) {
  const requestedSection = (await searchParams).section;
  const section = requestedSection === "designs" || requestedSection === "orders" ? requestedSection : "quotes";
  const user = await requireUser();
  const [orders, designs, quotes] = await Promise.all([
    getPool().query<{ id: string; tracking_token: string; status: string; total_cents: number; fulfillment_method: string; created_at: Date; product_names: string; product_slug: string | null; reorderable: boolean }>(`SELECT o.id,o.tracking_token,o.status,o.total_cents,o.fulfillment_method,o.created_at,string_agg(i.product_name, ', ' ORDER BY i.product_name) AS product_names,
      max(p.slug) AS product_slug,
      count(i.id)=1 AND bool_and(i.design_data IS NOT NULL AND p.status='published' AND p.ordering_enabled AND NOT p.age_restricted AND NOT c.age_restricted
        AND EXISTS (SELECT 1 FROM product_variants v WHERE v.product_id=p.id AND v.active AND v.base_price_cents IS NOT NULL)) AS reorderable
      FROM orders o JOIN order_items i ON i.order_id=o.id LEFT JOIN products p ON p.id=i.product_id LEFT JOIN categories c ON c.id=p.category_id
      WHERE o.user_id=$1 GROUP BY o.id ORDER BY o.created_at DESC LIMIT 50`, [user.id]),
    getPool().query<SavedRow>(`SELECT d.id,d.name,d.product_id,d.product_name,d.product_slug,d.updated_at,d.share_token,p.status AS product_status
      FROM saved_designs d LEFT JOIN products p ON p.id=d.product_id WHERE d.user_id=$1 ORDER BY d.updated_at DESC LIMIT 100`, [user.id]),
    getPool().query<QuoteRow>(`SELECT q.id,q.status,q.amount_cents,q.revision,q.sent_at,r.product_name,r.product_type,r.quantity
      FROM quotes q JOIN design_requests r ON r.id=q.design_request_id WHERE q.user_id=$1 AND r.user_id=$1 ORDER BY q.updated_at DESC LIMIT 50`, [user.id]),
  ]);
  return <main className="inner-page"><span className="eyebrow">YOUR SPACE</span><h1>Hello, {user.name}.</h1><p>Review quotes, keep designs ready to edit, and follow your orders.</p><div className="account-card"><div><strong>Account</strong><p>{user.email}</p></div><SignOutButton /></div>
    <nav className="account-section-nav" aria-label="Account sections"><Link href="/account?section=quotes" aria-current={section === "quotes" ? "page" : undefined}>My quotes</Link><Link href="/account?section=designs" aria-current={section === "designs" ? "page" : undefined}>My designs</Link><Link href="/account?section=orders" aria-current={section === "orders" ? "page" : undefined}>My orders</Link></nav>
    {section === "quotes" && <section className="account-quotes" aria-labelledby="account-quotes-title"><div className="account-section-head"><div><span className="eyebrow">CUSTOM PRINTING</span><h2 id="account-quotes-title">My quotes</h2><p>Review a price, accept it, or ask us to make changes.</p></div></div>{quotes.rows.length ? <div className="account-quote-grid">{quotes.rows.map((quote) => <article className="account-quote" key={quote.id}><div><span className="account-quote-status">{quote.status.replaceAll("_", " ")}</span><h3>{quote.product_name ?? quote.product_type} · {quote.quantity} items</h3><p>Quote #{quote.id.slice(0, 8)} · Revision {quote.revision}{quote.sent_at ? ` · ${dateTime(quote.sent_at)}` : ""}</p></div><div><strong>{euro(quote.amount_cents)}</strong><Link href={`/account/quotes/${quote.id}`}>{quote.status === "sent" ? "Review quote →" : "View quote →"}</Link></div></article>)}</div> : <div className="account-design-empty"><strong>No quotes yet</strong><p>When the team prices a design you submit while signed in, it will appear here.</p></div>}</section>}
    {section === "designs" && <section className="account-designs" aria-labelledby="account-designs-title"><div className="account-section-head"><div><span className="eyebrow">DESIGN LIBRARY</span><h2 id="account-designs-title">My designs</h2><p>Saved to your account so you can continue on another device.</p></div><Link className="button" href="/#products">Create a design</Link></div>
      {designs.rows.length ? <div className="account-design-grid">{designs.rows.map((design) => <article className="account-design" key={design.id}><div className="account-design-image"><Image src={`/api/saved-designs/${design.id}/preview`} alt={`Preview of ${design.name}`} width={1000} height={420} unoptimized /></div><div className="account-design-body"><span>{design.product_name}</span><h3>{design.name}</h3><p>Edited {dateTime(design.updated_at)}</p><div className="account-design-actions">{design.product_id && design.product_status === "published" ? <Link className="account-design-edit" href={`/design/${encodeURIComponent(design.product_slug)}?saved=${design.id}`}>Continue editing →</Link> : <span className="account-design-unavailable">Product unavailable</span>}<form action={duplicateDesign}><input type="hidden" name="id" value={design.id} /><button type="submit">Duplicate</button></form>{design.share_token ? <><ShareLink token={design.share_token} /><form action={stopSharingDesign}><input type="hidden" name="id" value={design.id} /><button type="submit">Stop sharing</button></form></> : <form action={shareDesign}><input type="hidden" name="id" value={design.id} /><button type="submit">Create share link</button></form>}<form action={deleteDesign}><input type="hidden" name="id" value={design.id} /><button type="submit" className="account-design-delete">Delete</button></form></div></div></article>)}</div> : <div className="account-design-empty"><strong>No saved designs yet</strong><p>Choose a product, add your artwork, then select “Save design” in the editor.</p><Link href="/#products">Explore products →</Link></div>}</section>}
    {section === "orders" && <section className="account-orders" aria-labelledby="account-orders-title"><h2 id="account-orders-title">My orders</h2>{orders.rows.length ? <ul>{orders.rows.map((order) => <li key={order.id}><strong>#{order.id.slice(0, 8)} · {order.product_names}</strong><span>{dateTime(order.created_at)} · {order.status.replaceAll("_", " ")} · {order.fulfillment_method} · {euro(order.total_cents)}</span><div className="account-order-actions"><Link href={`/track/${order.tracking_token}`}>Track order →</Link>{order.reorderable && order.product_slug && <Link href={`/design/${encodeURIComponent(order.product_slug)}?reorder=${encodeURIComponent(order.id)}#send-design`}>Order again →</Link>}</div></li>)}</ul> : <p>No orders yet.</p>}</section>}{user.role === "admin" && <Link className="button button-primary" href="/admin">Open admin dashboard</Link>}</main>;
}
